# Generated by Django 5.0.2 on 2024-02-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_enquiry_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
