# Generated by Django 5.0.2 on 2024-02-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_college_is_featured_course_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='admission',
            field=models.TextField(default='admission formalities here', max_length=500),
        ),
        migrations.AddField(
            model_name='college',
            name='affiliation',
            field=models.TextField(default='Affiliation details here', max_length=500),
        ),
        migrations.AddField(
            model_name='college',
            name='website',
            field=models.CharField(default='wwww.example.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
