# Generated by Django 5.0.2 on 2024-02-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_college_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='overview',
            field=models.TextField(default='course overview here', max_length=1000),
        ),
    ]
