# Generated by Django 5.0.2 on 2024-02-13 09:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_college_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegecourse',
            name='eligibility',
            field=ckeditor.fields.RichTextField(default='Eligibilty criteria'),
        ),
    ]
