# Generated by Django 5.0.2 on 2024-02-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_college_address_alter_college_admission_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collegecourse',
            unique_together={('college', 'course')},
        ),
    ]
