# Generated by Django 5.0.2 on 2024-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_collegecourse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
